services:
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: seanime-vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8888:8888" # HTTP proxy port
      - "8388:8388" # SOCKS proxy port
      - "2500:43211" # Seanime backend port
      - "3000:3000" # Seanime frontend port
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER=5254230649909803
      - OPENVPN_PASSWORD=x
      - SERVER_COUNTRIES=Sweden
    restart: unless-stopped
    volumes:
      - ./gluetun:/gluetun

  animechanica:
    build:
      context: .
      dockerfile: Dockerfile.script
    container_name: animechanica
    restart: unless-stopped
    volumes:
      - /aeternae/configurations/animechanica/data:/app/data
      - /aeternae/theater/anime:/media/anime
      - /aeternae/theater/dl_anime:/media/dl_anime
    environment:
      - DATA_DIR=/app/data
    # Connect through the VPN container
    network_mode: "service:vpn"
    depends_on:
      - vpn

volumes:
  data:
    driver: local
  gluetun:
    driver: local
