version: '3.8'

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "43211:43211"  # Seanime
      - "8085:8085"    # qBittorrent
    volumes:
      - /aeternae/configurations/animechanica/mullvad:/gluetun/mullvad:Z
    environment:
      # VPN settings
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER_FILE=/gluetun/mullvad/mullvad_userpass.txt
      - SERVER_COUNTRIES=Switzerland
      - SERVER_CITIES=Zurich
      
      # DNS settings for faster resolution
      - DOT=off
      - DNS_KEEP_NAMESERVER=off
      - DNS_ADDRESS=1.1.1.1

      - LOG_LEVEL=info
      
      # Timezone
      - TZ=America/Los_Angeles
    restart: unless-stopped

  seanime:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seanime
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    volumes:
      - /aeternae/configurations/animechanica/data:/data:Z
      - /aeternae/theater/anime/completed/:/media/anime:Z
      - /aeternae/library/manga/completed/:/media/manga:Z
      - /aeternae/theater/dl_anime/:/media/dl_anime:Z
      - /aeternae/library/dl_manga/:/media/dl_manga:Z
      - /aeternae/configurations/animechanica/qbittorrent:/root/.config/qBittorrent:Z
    environment:
      - TZ=America/Los_Angeles
    restart: unless-stopped